### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by spfmoby** [Ecodev/natural-gallery-js#10]
Hi

Some demo links in the readme are broken, ie https://ecodev.ch/natural-gallery/demo/light.html
the whole "light" stuff seems outdated (no more xxx.light.js or .css in the sources)

It could be usefull to take them back to have more ways to customize the photoswipe part, for example display the share buttons, or at least give us some examples to configure the embedded version of photoswipe through natural-gallery.

Thanks

**Comment by sambaptista** [comment]
Actually photoswipe can be customised by the template in the html. Photoswipe options in the javascript side are not yet supported. I'm aware there is a lack of flexibility by now.

The light build has no impact on customisation, it's just a different bundle. It finds out it was not used, and to avoid too much maintenance I've removed it. It would be usefull only if you were already using photoswipe before using natural-gallery-js.

I'll update docs to remove those examples.
