### ISSUE TITLE
fullscreen can't advance past to first load

### ISSUE THREAD

**Issue by spfmoby** [Ecodev/natural-gallery-js#11]
if the minRowsAtStart parameter is not set to a bigg value (at least the total number of pictures) if you switch to fullscreen view before reaching the end of the page, you can only advance to the last already loaded picture (before switching to fullscreen).

Step to reproduce : 
1/ go to your demo page : https://ecodev.ch/natural-gallery/demo/ it says for example 9/80 pictures 
2/ clic on the first picture to switch to fullscreen, on the top left you can read 1/9
3/ advance to the 9th picture for example using the arrows, try to go to the 10th picture, it comes back to the first one.

A way to get around is to set the minRowsAtStart parameter to 9999 for example, this way all the thumbnails are loaded right from the beginning... it solves the problem at the expense of bandwidth...

**Comment by sambaptista** [comment]
Hi, thx for your report. I could reproduce.

A recent change seems to have broken the pagination when navigating in the lightbox. I'll check it.

**Comment by sambaptista** [comment]
Issue fixed and will be published on next release, that will be a major version. If you really need this fixed asap, you can already use master branch. Refer to sandbox/index.html. Demo is not updated yet.

**Comment by spfmoby** [comment]
I reopen the bug because I discovered something that seems still related to the lazy loading number... 
on an iPad (2018, iOS 12, Safari), when I use the lazyloading, for example set to 20 pictures, there are problems to load all the pictures when I scroll down. If y set the parameter to something like 2000 (I have around 500-1500 pictures to load) there are no problems.
