### ISSUE TITLE
Install without npm and yarn

### ISSUE THREAD

**Issue by Tsyklop** [Ecodev/natural-gallery-js#13]
How to install your lib without npm and yarn?

**Comment by sambaptista** [comment]
On yarn website (https://yarnpkg.com/en/package/natural-gallery-js) you can find a section on the right sidebar "CDNs" and download the last release from different sources.

On jsdelivr for example you can find a download button on the right of the name. 
https://www.jsdelivr.com/package/npm/natural-gallery-js
