### ISSUE TITLE
Responsive Square

### ISSUE THREAD

**Issue by SadlerJohnson** [Ecodev/natural-gallery-js#2]
Natural mode is responsive but Square mode is not. Square thumbnails per row is set to a single value (default 4).  Can the Square mode start from a max value then reduce to 1/row at small screen sizes?

**Comment by sambaptista** [comment]
Hello, thank you for your suggestion,

I'll investigate what can be done for a better responsive.

**Comment by sambaptista** [comment]
I've updated the gallery and the typo3 extension. 

In typo3, you can now leave the field "Pictures per row" empty. The field "Maximum row height" will become applicable. This way, natural and square format work on same approach with same logic.

You can find a demo here : https://ecodev.ch/natural-gallery/demo/square-responsive.html

Enjoy :)
