### ISSUE TITLE
Enhancement: Optional focal point on thumbnails

### ISSUE THREAD

**Issue by nielsrune** [Ecodev/natural-gallery-js#24]
I have not created resized thumbnails for the pictures in my gallery, so the source for the enlarged and thumbnail are the same.

The gallery shrinks the images just fine, however. Wonder why the necessity of the thumbnail part of the json. Is it just for optional bandwidth saving / workload on the client?

One thing that might be great is an optional focal point setting for each image, so that and image thumbnail would not be automatically resized from the center but from the given focal point.

To better explain see this demo from a jQuery plugin: https://jonom.github.io/jquery-focuspoint/demos/helper/index.html

Hopefully it is self explaining.

**Comment by sambaptista** [comment]
Released in 4.1.0 with new cover option
