### ISSUE TITLE
Npm has old version

### ISSUE THREAD

**Issue by qandeelabbassi** [Ecodev/natural-gallery-js#26]
Why is this library not updated on npm or yarn

**Comment by sambaptista** [comment]
Probably you're using the old package named `natural-gallery-js`. It has been renamed `@ecodev/natural-gallery-js`.  

The old one has been preserved for projects that use it as it was.

I close the issue, feel free to re-open if needed.

**Comment by PowerKiKi** [comment]
I think `natural-gallery-js` should be [marked as deprecated](https://docs.npmjs.com/cli/deprecate) with a message pointing to `@ecodev/natural-gallery-js`, to avoid confusion for new users and suggest migrating for existing users.
