### ISSUE TITLE
IE & iOS

### ISSUE THREAD

**Issue by SadlerJohnson** [Ecodev/natural-gallery-js#3]
Hi Sam,
Your demo pages are not showing the gallery on IE11 and any browser on iOS. The data for the gallery seems to be rendered in the source of the page in each case.
https://ecodev.ch/natural-gallery/demo/

The same is happening with our own instance of Natural Gallery.
http://eleven.ort.org/gallery/

Thank you for improving the responsive square feature.
Best wishes

**Comment by sambaptista** [comment]
Hi Sadler,

It's not a bug, it's a feature :)

iOS9 and older + IE11 and older represents ~4% of internet traffic. These browsers don't always respect the W3C standards, that's a reason I've chosen to drop support for this versions. This allow me to use a js compilation method that **reduces the file size for the other users**.

I'd like to stay focused on the future and features, and not allocate too much time to old browsers. I hope you understand.

Thanks again for using this lib and sending feedbacks. 
Best regards !
