### ISSUE TITLE
NaturalGallery.Natural is not a constructor

### ISSUE THREAD

**Issue by alistair-rodrigues** [Ecodev/natural-gallery-js#31]
Hello,

I am trying to implement natural gallery. But it's not initialising. 
What am I doing wrong?

HTML Code ->

	<head>
		<link rel="stylesheet" href="/vendor/stylesheets/natural-gallery.css" />
		<link rel="stylesheet" href="/vendor/stylesheets/natural-themes/natural.css" />
		<script src="/vendor/natural-gallery.js" defer></script>
	</head>
	<body>
		<div id="gallery">

		</div>
		<script type="text/javascript">
			window.addEventListener('load', function() {
				var elementRef = document.getElementById('gallery');
			  var gallery = new NaturalGallery.Natural(elementRef); // or
			  var items = [
			       {
			          thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
			          enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
			          enlargedWidth: 881,
			          enlargedHeight: 587,
			          title: "Testing images", // Title for the label or button
			          color: "#f0f0f0" // HEX color for background before image display
			      },
				      {
				         thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
				         enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
				         enlargedWidth: 881,
				         enlargedHeight: 587,
				         title: "Testing images", // Title for the label or button
				         color: "#f0f0f0" // HEX color for background before image display
				     },
						 {
				        thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
				        enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
				        enlargedWidth: 881,
				        enlargedHeight: 587,
				        title: "Testing images", // Title for the label or button
				        color: "#f0f0f0" // HEX color for background before image display
				    },
						{
				       thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
				       enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
				       enlargedWidth: 881,
				       enlargedHeight: 587,
				       title: "Testing images", // Title for the label or button
				       color: "#f0f0f0" // HEX color for background before image display
				   	},
						{
				      thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
				      enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
				      enlargedWidth: 881,
				      enlargedHeight: 587,
				      title: "Testing images", // Title for the label or button
				      color: "#f0f0f0" // HEX color for background before image display
				  	},
						{
				     thumbnailSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=42f6316b25d69a6fe7c71ca2b03b8743", // link to thumbnail image
				     enlargedSrc: "https://images.unsplash.com/photo-1520257328559-2062fc7de0b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyOTN9&s=a2281ba006a4428c117b6b2e2dfb8ba1", // link to enlarged image
				     enlargedWidth: 881,
				     enlargedHeight: 587,
				     title: "Testing images", // Title for the label or button
				     color: "#f0f0f0" // HEX color for background before image display
				 		}
			  ];
			  // Set the entire collection
			  gallery.setItems(items);
			});
		</script>
	</body>

**Comment by sambaptista** [comment]
How did you get files, and what version are you using ? 

Please consider creating jsfiddle/stackoverflow/codepen.

**Comment by alistair-rodrigues** [comment]
I got the files through npm.
Copied the files from the dist folder.
Version is 2.8.0.

I will try to make a jsfiddle and post a link here.

**Comment by sambaptista** [comment]
You've installed lib from deprecated natural-gallery-js package. Use @ecodev/natural-gallery-js. Actual version is 4.1.0 

https://ecodev.github.io/natural-gallery-js/docs-getting-started.html

**Comment by nguyenngoc2505** [comment]
Hello, I've same problem when implement NaturalGallery from cdn.
This is my codepen link. Please take a look. Thanks for all support.
https://codepen.io/rubyfah/pen/xxLGOBe
