### ISSUE TITLE
Edge and Safari issue

### ISSUE THREAD

**Issue by Lovor01** [Ecodev/natural-gallery-js#37]
Hello,
I cannot get gallery to work with Microsoft Edge 44 and MacOs Safari. Just the first image thumbnail is being loaded.
See e.g. https://makeiteasy.hr/fototeka/autor.php?autor=Vranic&lang=en

**Comment by Lovor01** [comment]
Update: I managed to fix the issue, but not on original typescript code (I am not used to typescript tools, so I was unable to obtain source code, only definitions)
Here is the fix in prettifyed javascript:
`          n.addEventListener("scroll", (function () {
            r(), s();
            var t = e.elementRef.offsetTop + e.elementRef.offsetHeight + e.options.infiniteScrollOffset,
              n = o.scrollTop - (o.clientTop || 0),
              i = o.clientHeight,
              l = n - e.old_scroll_top;
            e.old_scroll_top = n, l > 0 && n + i >= t && e.onScroll()
          }))`
the o.scrollTop should be replaced by window.scrollY. That is, because old Edge and Safari do not respect scrollTop w3 consortium [definition](https://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#dom-element-scrolltop) of scrollTop on root html element.

**Comment by sambaptista** [comment]
Thx, I'll check this week.
