### ISSUE TITLE
SVG icon not shown

### ISSUE THREAD

**Issue by Lovor01** [Ecodev/natural-gallery-js#38]
In my project, this part of SVG icon for showing more images (down arrow) does not get loaded, compared to your example:
![image](https://user-images.githubusercontent.com/33687174/77238827-2539b880-6bd4-11ea-8826-958e060c4c61.png)
Instead I get only empty SVG container, and SVG is not shown.

**Comment by sambaptista** [comment]
Sorry for late answer. Refering to readme : 

> Found a bug ?
> Create an issue where you report what you observe, what you expect to observe, and the context of usage, as well as your browser and it's version.

I need more information than you give. Gallery used ? version ? code ? did you include the svg in the template ? how many galleries do you have in the page ? Are you in infinite scroll mode ?
