### ISSUE TITLE
PhotoSwipe Options

### ISSUE THREAD

**Issue by plouj** [Ecodev/natural-gallery-js#4]
Is there a way to use custom PhotoSwipe options? From what I can tell they are hard-coded in https://github.com/Ecodev/natural-gallery-js/blob/master/app/js/Item.ts#L304

**Comment by sambaptista** [comment]
You're right, they're hardcoded at the moment and there is no way to override them. 
I'm going to work on this lib soon (two weeks). I add this to the todo list.

**Comment by spfmoby** [comment]
Hope you can find a little time to work on that :) Thanks in advance. Interested too

**Comment by sambaptista** [comment]
It has just been pushed :)

But you'll have to wait the release of the next major version 4.0.0. Coming soon.

**Comment by sambaptista** [comment]
Released including this demand.

**Comment by spfmoby** [comment]
Thank you for your work.
I managed to update my gallery to include your v4.0.0 version but I still have problems with the share button.
The PhotoSwype options seems to be passed to PhotoSwype, for example "escKey: true" or "escKey: false" are changing the sc key behavious when a picture is opened in photoswype... but I am not able to maje the share button appear.
I tried the shareEl: true/false and the whole sharebuttons list, for example:

var PSoptions = {
			escKey: true,
			shareEl: true,
			shareButtons: [
    {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}'},
    {id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}'},
    {id:'pinterest', label:'Pin it', url:'http://www.pinterest.com/pin/create/button/?url={{url}}&media={{image_url}}&description={{text}}'},
    {id:'download', label:'Download image', url:'{{raw_image_url}}', download:true}
],
} ;

/.../
var gallery = new NaturalGallery.Natural(elementRef, options, photoswipeRef);

But the buttons never shows up :(

**Comment by spfmoby** [comment]
Of course I find the solution 5 minutes after my post.
To be able to see the share button, it has to be initialized in the html template by adding 
<button class="pswp__button pswp__button--share" title="Share"></button> with the other buttons !
