### ISSUE TITLE
Natural.ts:25 Uncaught TypeError: Cannot read property 'rowHeight' of undefined

### ISSUE THREAD

**Issue by sahilbest999** [Ecodev/natural-gallery-js#40]
Hello i'm a beginner in JS and i've been trying to fix the problem but i'm not sure what's happening 
 
window.addEventListener('load', function() {
  var  elementRef = document.getElementById('gallery');
  var  gallery = new NaturalGallery.Natural(elementRef); //Error on this line
  var  gallery.init();
});

I'm using Edge Browser [version : 81.0.416.68].
Error Image : 
![image](https://user-images.githubusercontent.com/57249267/81283041-a7454a00-9079-11ea-91db-bf8aa0d9776d.png)

**Comment by sambaptista** [comment]
Hello sorry for delay, and for uncomplete docs. I'll fix that.

A minimum requirement for Natural format is the option rowHeight that determines the maximum height of a row. You should instantiate the library like this : 

```js
 var gallery = new NaturalGallery.Natural(elementRef, {rowHeight: 300});  // add option
```

**Comment by sahilbest999** [comment]
Nice
