### ISSUE TITLE
Uncaught TypeError: Qe(...) is not a constructor

### ISSUE THREAD

**Issue by Gausoft** [Ecodev/natural-gallery-js#59]
Hi, thanks for this clean library you've developed.
I imported "natural-gallery-js" hole folder into my project but I'am just using css and js libraries mentionned in the demo..
But I'am facing the issue bellow.

![Screenshot from 2021-06-12 22-03-29](https://user-images.githubusercontent.com/26385667/121789960-128d1400-cbca-11eb-9a60-f9f043322772.png)

 I don't even understand why the issue is located in typescript file.
 I need your help

**Comment by PowerKiKi** [comment]
Be sure to follow https://ecodev.github.io/natural-gallery-js/docs-getting-started.html, or see a real complete example on https://stackblitz.com/edit/js-dzmjzq?file=index.html (but do **not** use hosted files on https://ecodev.github.io for production use, it **will** break in the future).

If that does not work, share a reproducible case on https://stackblitz.com/
