### ISSUE TITLE
Scretching image

### ISSUE THREAD

**Issue by Gausoft** [Ecodev/natural-gallery-js#60]
Hello
After including assets as mentioned [here](https://github.com/Ecodev/natural-gallery-js/issues/59#issuecomment-860143937)   in my code I notice that images are scretched.
Any idea why this behavior?

![Screenshot from 2021-06-14 09-02-07-1-1](https://user-images.githubusercontent.com/26385667/121867568-9ab90980-ccef-11eb-8b7f-9bccb2d4c116.png)

How to override applied css in order to display correctely zoomed images?
Thanks

**Comment by mx781** [comment]
For anyone stumbling upon this in the future: for me it turned out to be incorrectly configured `enlargedWidth` and `enlargedHeight` - double check the data you're passing to `setItems` / `addItem`!
