### ISSUE TITLE
How to customise photoswipe

### ISSUE THREAD

**Issue by johtso** [Ecodev/natural-gallery-js#75]
I'm wanting to add an extra button to the photoswipe lightbox, but I'm not sure how to get the right reference to be able to do it.

I'm trying to follow the instructions here: https://photoswipe.com/adding-ui-elements/

It involves listening for an event on a `PhotoSwipeLightbox` object.. but I'm not sure how to do that when everything's set up but natural.

**Comment by kfsz** [comment]
Hey, 

https://photoswipe.com/adding-ui-elements/ refers to PhotoSwipe v5 (which is pretty new and was released / went out of beta just 12 days ago - https://github.com/dimsemenov/PhotoSwipe/releases/tag/v5.2.2)

natural-gallery-js currently uses PhotoSwipe v4 for which docs are located at https://photoswipe.com/v4-docs/getting-started.html

I think that to add a button to PhotoSwipe v4 you would have to add it to HTML template (like here - https://ecodev.github.io/natural-gallery-js/docs-options.html#lightbox)

(also, I ported natural-gallery-js to PhotoSwipe v5 just yesterday and above instructions should work there - I plan to create a pull request for that later today)

**Comment by johtso** [comment]
@kfsz thanks for the help!

So I added an extra button in my template.. but it wasn't obvious how to get the currently visible item.

Eventually managed to figure out a way to get a reference to the `PhotoSwipe` object so I could get the current item. Not super pretty but works.

```typescript
  var photoswipe: PhotoSwipe<any>;
  var linkButton = document.getElementsByClassName('link_button')[0] as HTMLElement;
  gallery.addEventListener('zoom', function (evt) {
    photoswipe = evt.detail.photoswipe;
    linkButton.addEventListener('click', function (evt) {
      let currentItem = photoswipe.currItem;
      console.log(currentItem);
    });
  });
```

Awesome to hear you're close to having photoswipe v5 supported!

**Comment by kfsz** [comment]
@johtso glad to hear you got it working!

and yeah, i think i used something similar before for detecting which item is currently selected

in my case it was this:
```js 
naturalGalleryObj.addEventListener("zoom", (ev) => {
    ev.detail.photoswipe.listen("beforeChange", () => {
        selectedPost =
            naturalGalleryObj._collection[
                ev.detail.photoswipe.getCurrentIndex()
            ].model;
    });
    ev.detail.photoswipe.listen("close", () => {
        selectedPost = {};
    });
    selectedPost = ev.detail.item;
});
```

didn't know PS had `currItem` property, good to know! - doesn't seem like it exists in v5 though
maybe because of a different approach and item data array not being necessary, with PS inferring image data thru HTML properties by default  - dunno, not that familiar with PS though 😛 

good thing you reminded me that there should be an easier way to get current PS image - added `photoSwipeCurrentItem` getter to my PR 😛
