### ISSUE TITLE
Can't manage to initilaize gallery

### ISSUE THREAD

**Issue by vinhor** [Ecodev/natural-gallery-js#99]
No matter how I try, i get always "import declarations may only appear at top level of a module" syntax error and the gallery doesnt show

**Comment by sambaptista** [comment]
Please provide context/code about your environment.

**Comment by vinhor** [comment]
Firefox 129.0, Fedora Linux 40 (Kernel 6.10.3). Natural gallery installed with yarn
Code is here: [https://drive.google.com/file/d/1-XFjM2ExaKB4DYmiyUgoCns0GKMSjNV7/view?usp=sharing](https://drive.google.com/file/d/1-XFjM2ExaKB4DYmiyUgoCns0GKMSjNV7/view?usp=sharing)
